[package]
name = "axum-todo"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
tokio = { version = "1.44.1", features = ["full", "macros", "rt-multi-thread"] }
tower = "0.5.2"
serde = "1.0.219"
