[package]
name = "application"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
sqlx.workspace = true
uuid.workspace = true
# tokio.workspace = true
serde.workspace = true
# dotenv.workspace = true
# chrono.workspace = true
domain = { path = "../domain" }
